# Explore Madrid Accident Data

This notebook explores the raw CSV data from Madrid's Open Data portal to decide which columns should be stored in the new `accident_participants` table.

In [1]:
import pandas as pd
import io
import requests
from pathlib import Path

# Sample URL for 2024 accidents
URL_2024 = "https://datos.madrid.es/dataset/300228-0-accidentes-trafico-detalle/resource/300228-2-accidentes-trafico-detalle-csv/download/300228-2-accidentes-trafico-detalle-csv.csv"

print("Downloading 2024 data...")
resp = requests.get(URL_2024)
df = pd.read_csv(io.BytesIO(resp.content), sep=";", encoding="utf-8-sig")

# Normalize columns
df.columns = [c.lower().strip().replace(" ", "_") for c in df.columns]

print(f"Total records: {len(df)}")
print(f"Unique accidents: {df['num_expediente'].nunique()}")
df.head()

Downloading 2024 data...
Total records: 49340
Unique accidents: 20698

,num_expediente,fecha,hora,localizacion,numero,cod_distrito,distrito,tipo_accidente,estado_meteorológico,tipo_vehiculo,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,coordenada_x_utm,coordenada_y_utm,positiva_alcohol,positiva_droga
0,2023S040280,04/01/2024,14:09:00,AVDA. NICETO ALCALA ZAMORA / AUTOV. M-11,3,16,HORTALEZA,Colisión fronto-lateral,Lluvia débil,Motocicleta > 125cc,Conductor,De 55 a 59 años,Hombre,2.0,Ingreso inferior o igual a 24 horas,444913.0,4481427.0,N,NaN
1,2023S040280,04/01/2024,14:09:00,AVDA. NICETO ALCALA ZAMORA / AUTOV. M-11,3,16,HORTALEZA,Colisión fronto-lateral,Lluvia débil,Turismo,Conductor,De 55 a 59 años,Mujer,14.0,Sin asistencia sanitaria,444913.0,4481427.0,N,NaN
2,2023S040309,15/02/2024,14:05:00,CALL. TESORO / CALL. MINAS,18,1,CENTRO,Colisión fronto-lateral,Lluvia débil,Bicicleta,Conductor,De 25 a 29 años,Hombre,7.0,Asistencia sanitaria sólo en el lugar del acci...,440123.0,4475170.0,N,NaN
3,2023S040309,15/02/2024,14:05:00,CALL. TESORO / CALL. MINAS,18,1,CENTRO,Colisión fronto-lateral,Lluvia débil,Motocicleta hasta 125cc,Conductor,De 35 a 39 años,Hombre,14.0,Sin asistencia sanitaria,440123.0,4475170.0,N,NaN
4,2023S040310,18/02/2024,10:40:00,GTA. RUIZ JIMENEZ / CALL. SAN BERNARDO,3,7,CHAMBERÍ,Colisión lateral,Despejado,Turismo,Conductor,De 25 a 29 años,Hombre,NaN,NaN,440137.0,4475721.0,N,NaN

## Column Analysis

Let's look at the available columns and some sample values for each.

In [2]:
analysis = []
for col in df.columns:
    analysis.append({
        "Column": col,
        "Unique Values": df[col].nunique(),
        "Sample Values": ", ".join(map(str, df[col].dropna().unique()[:5])),
        "Nulls": df[col].isna().sum()
    })

pd.DataFrame(analysis)

,Column,Unique Values,Sample Values,Nulls
0,num_expediente,20698,"2023S040280, 2023S040309, 2023S040310, 2023S04...",0
1,fecha,366,"04/01/2024, 15/02/2024, 18/02/2024, 25/02/2024...",0
2,hora,1256,"14:09:00, 14:05:00, 10:40:00, 17:20:00, 14:25:00",0
3,localizacion,15131,"AVDA. NICETO ALCALA ZAMORA / AUTOV. M-11, CALL...",0
4,numero,1759,"3, 18, 93, 14, 0",0
5,cod_distrito,21,"16, 1, 7, 6, 10",0
6,distrito,21,"HORTALEZA, CENTRO, CHAMBERÍ, TETUÁN, LATINA",0
7,tipo_accidente,12,"Colisión fronto-lateral, Colisión lateral, Alc...",5
8,estado_meteorológico,7,"Lluvia débil, Despejado, Nublado, Se desconoce...",5916
9,tipo_vehiculo,32,"Motocicleta > 125cc, Turismo, Bicicleta, Motoc...",394
10,tipo_persona,3,"Conductor, Pasajero, Peatón",0
11,rango_edad,18,"De 55 a 59 años, De 25 a 29 años, De 35 a 39 a...",0
12,sexo,3,"Hombre, Mujer, Desconocido",0
13,cod_lesividad,9,"2.0, 14.0, 7.0, 1.0, 3.0",21996
14,lesividad,9,"Ingreso inferior o igual a 24 horas, Sin asist...",21996
15,coordenada_x_utm,10131,"444913.0, 440123.0, 440137.0, 440709.0, 433983.0",6
16,coordenada_y_utm,10997,"4481427.0, 4475170.0, 4475721.0, 4480102.0, 44...",6
17,positiva_alcohol,2,"N, S",167
18,positiva_droga,1,1.0,49137

In [7]:
for col in df.columns:
    if df[col].nunique() < 35:
        print(f"Column: {col}")
        print(f"Values: {', '.join(map(str, df[col].dropna().unique()))}")
        print(f"Nulls: {df[col].isna().sum()}")
        print("-" * 30)

Column: cod_distrito
Values: 16, 1, 7, 6, 10, 9, 3, 13, 14, 11, 4, 5, 19, 2, 8, 12, 18, 21, 17, 20, 15
Nulls: 0
------------------------------
Column: distrito
Values: HORTALEZA, CENTRO, CHAMBERÍ, TETUÁN, LATINA, MONCLOA-ARAVACA, RETIRO, PUENTE DE VALLECAS, MORATALAZ, CARABANCHEL, SALAMANCA, CHAMARTÍN, VICÁLVARO, ARGANZUELA, FUENCARRAL-EL PARDO, USERA, VILLA DE VALLECAS, BARAJAS, VILLAVERDE, SAN BLAS-CANILLEJAS, CIUDAD LINEAL
Nulls: 0
------------------------------
Column: tipo_accidente
Values: Colisión fronto-lateral, Colisión lateral, Alcance, Choque contra obstáculo fijo, Colisión múltiple, Colisión frontal, Atropello a persona, Caída, Solo salida de la vía, Otro, Vuelco, Atropello a animal
Nulls: 5
------------------------------
Column: estado_meteorológico
Values: Lluvia débil, Despejado, Nublado, Se desconoce, LLuvia intensa, Granizando, Nevando
Nulls: 5916
------------------------------
Column: tipo_vehiculo
Values: Motocicleta > 125cc, Turismo, Bicicleta, Motocicleta hasta 125cc, Camión rígido, Maquinaria de obras, Furgoneta, VMU eléctrico, Autobús, Bicicleta EPAC (pedaleo asistido), Todo terreno, Otros vehículos sin motor, Autobús articulado, Ciclomotor, Sin especificar, Otros vehículos con motor, Vehículo articulado, Autocaravana, Tractocamión, Ciclo, Autobus EMT, Semiremolque, Moto de tres ruedas > 125cc, Cuadriciclo ligero, Cuadriciclo no ligero, Moto de tres ruedas hasta 125cc, Patinete no eléctrico, Remolque, Ambulancia SAMUR, Ciclo de motor L1e-A, Ciclomotor de dos ruedas L1e-B, Ciclomotor de tres ruedas
Nulls: 394
------------------------------
Column: tipo_persona
Values: Conductor, Pasajero, Peatón
Nulls: 0
------------------------------
Column: rango_edad
Values: De 55 a 59 años, De 25 a 29 años, De 35 a 39 años, De 50 a 54 años, De 60 a 64 años, De 21 a 24 años, De 30 a 34 años, De 18 a 20 años, Desconocido, De 40 a 44 años, De 15 a 17 años, De 45 a 49 años, Más de 74 años, De 65 a 69 años, De 70 a 74 años, Menor de 5 años, De 6 a 9 años, De 10 a 14 años
Nulls: 0
------------------------------
Column: sexo
Values: Hombre, Mujer, Desconocido
Nulls: 0
------------------------------
Column: cod_lesividad
Values: 2.0, 14.0, 7.0, 1.0, 3.0, 6.0, 5.0, 4.0, 77.0
Nulls: 21996
------------------------------
Column: lesividad
Values: Ingreso inferior o igual a 24 horas, Sin asistencia sanitaria, Asistencia sanitaria sólo en el lugar del accidente, Atención en urgencias sin posterior ingreso, Ingreso superior a 24 horas, Asistencia sanitaria inmediata en centro de salud o mutua, Asistencia sanitaria ambulatoria con posterioridad, Fallecido 24 horas, Se desconoce
Nulls: 21996
------------------------------
Column: positiva_alcohol
Values: N, S
Nulls: 167
------------------------------
Column: positiva_droga
Values: 1.0
Nulls: 49137
------------------------------

## Typical participant-level columns

Based on the data, these columns vary per person for the same `num_expediente`:

In [3]:
participant_cols = [
    "tipo_persona",
    "rango_edad",
    "sexo",
    "cod_lesividad",
    "lesividad",
    "tipo_vehiculo"
]

# Show an example of multiple participants in one accident
multi_participant_ids = df['num_expediente'].value_counts()
example_id = multi_participant_ids[multi_participant_ids > 1].index[0]

print(f"Example accident ID with multiple participants: {example_id}")
df[df['num_expediente'] == example_id][participant_cols]

Example accident ID with multiple participants: 2024S026225

,tipo_persona,rango_edad,sexo,cod_lesividad,lesividad,tipo_vehiculo
33369,Conductor,De 25 a 29 años,Hombre,6.0,Asistencia sanitaria inmediata en centro de sa...,Sin especificar
33370,Conductor,Desconocido,Desconocido,NaN,NaN,Sin especificar
33371,Conductor,Desconocido,Desconocido,NaN,NaN,Sin especificar
33372,Conductor,Desconocido,Desconocido,NaN,NaN,Sin especificar
33373,Pasajero,De 30 a 34 años,Hombre,5.0,Asistencia sanitaria ambulatoria con posterior...,Sin especificar
33374,Conductor,Desconocido,Desconocido,NaN,NaN,Todo terreno
33375,Conductor,De 25 a 29 años,Hombre,14.0,Sin asistencia sanitaria,Turismo
33376,Conductor,De 35 a 39 años,Hombre,5.0,Asistencia sanitaria ambulatoria con posterior...,Turismo
33377,Conductor,De 35 a 39 años,Hombre,6.0,Asistencia sanitaria inmediata en centro de sa...,Turismo
33378,Conductor,De 40 a 44 años,Hombre,3.0,Ingreso superior a 24 horas,Turismo
33379,Conductor,De 50 a 54 años,Desconocido,NaN,NaN,Turismo
33380,Conductor,De 65 a 69 años,Hombre,14.0,Sin asistencia sanitaria,Turismo
33381,Conductor,Desconocido,Desconocido,NaN,NaN,Turismo
33382,Conductor,Desconocido,Desconocido,NaN,NaN,Turismo
33383,Conductor,Desconocido,Desconocido,NaN,NaN,Turismo
33384,Conductor,Desconocido,Desconocido,NaN,NaN,Turismo
33385,Conductor,Desconocido,Desconocido,NaN,NaN,Turismo
33386,Conductor,Desconocido,Desconocido,NaN,NaN,Turismo
33387,Conductor,Desconocido,Desconocido,NaN,NaN,Turismo
33388,Conductor,Desconocido,Desconocido,NaN,NaN,Turismo
33389,Pasajero,De 30 a 34 años,Hombre,6.0,Asistencia sanitaria inmediata en centro de sa...,Turismo
33390,Pasajero,De 40 a 44 años,Hombre,6.0,Asistencia sanitaria inmediata en centro de sa...,Turismo